qsub:
	qsub modeling.pbs

clean:
	rm -f src.* surf.* VEL_INT wtw.* stderr stdout

#run:
#	cp wtw_model.para ../../../src/modeling
#	cd ../../../src/modeling;make clean;make
#	mpirun -np 2 ../../../src/executables/a2d.x

