from rsf.proj import *

# read source wavelet input
#Flow('src','/storage/home/tuz47/work/mwt/mwt/run/modeling/model1/src.dat',
#          'echo in=${SOURCES[0]} n1=1251 d1=0.0008 o1=0 n2=1 data_format=float esize=4')
#Result('src', 'graph unit1=s label1=time')

# read velocity file to plot
#


 
import os
f = []
for (dirpath, dirnames,filenames) in os.walk("./"):
    for filename in filenames:
        if filename.endswith(".su"):
            f.append(filename)
 

for file in f:
    name = file.split(".")[0]
    print(name)    

    Flow(name,file,'suread suxdr=y endian=0 | put label1=time label2=distance unit1=s unit2=m')
    Result(name,'grey scalebar=y color=i title='+name)

    #End()


